import type { Template } from '$lib/types';

export const creatures = {
	druid: {
		name: 'druid',
		description: 'Attacks for 0 damage and 2 turns of poison. Summons animals.',
		ai: {
			abilities: [{ ability: 'druidSummon', cooldown: 10, countsAsTurn: true, currentCooldown: 5 }],
		},
		attack: { damage: 0, inflicts: { poisoned: 2 } },
		glyph: { char: 'D', class: 'font-creature text-green-300 z-50' },
		hp: { current: 4, max: 4 },
		statuses: {},
		team: 'enemy',
		threat: 4,
	},
	dwarf: {
		name: 'dwarf',
		description: 'Attacks for 2 damage. Armored.',
		ai: { abilities: [] },
		attack: { damage: 1 },
		glyph: { char: 'D', class: 'font-creature text-stone-400 z-50' },
		hp: { current: 3, max: 3 },
		statuses: { armored: true },
		team: 'enemy',
		threat: 2,
	},
	eagle: {
		name: 'eagle',
		description: 'Attacks for 1 damage. Can move and attack.',
		ai: { abilities: [], canMoveAndAttack: true },
		attack: { damage: 1 },
		glyph: { char: 'E', class: 'font-creature text-stone-400 z-50' },
		hp: { current: 2, max: 2 },
		statuses: { floating: true },
		team: 'enemy',
		threat: 1,
	},
	fiend: {
		name: 'fiend',
		synonyms: ['demon', 'devil'],
		description: 'Creates flames beneath adjacent enemies',
		ai: {
			abilities: [
				{
					ability: 'fiendFlame',
					cooldown: 0,
					currentCooldown: 0,
					countsAsTurn: true,
				},
			],
		},
		attack: { damage: 1 },
		glyph: { char: 'F', class: 'font-creature text-red-400 z-50' },
		hp: { current: 4, max: 4 },
		statuses: {},
		team: 'enemy',
		threat: 3,
	},
	giant: {
		name: 'giant',
		synonyms: ['titan'],
		description: 'Attacks for 2 damage. Nothing special, just lots of health.',
		ai: { abilities: [] },
		attack: { damage: 1 },
		glyph: { char: 'G', class: 'font-creature text-rose-300 z-50' },
		hp: { current: 20, max: 20 },
		statuses: {},
		team: 'enemy',
		threat: 5,
	},
	golem: {
		name: 'golem',
		description: 'Attacks for 1 damage. Armored.',
		ai: { abilities: [] },
		attack: { damage: 1 },
		glyph: { char: 'G', class: 'font-creature text-slate-300 z-50' },
		hp: { current: 10, max: 10 },
		statuses: { armored: true },
		team: 'enemy',
		threat: 5,
	},
	hyena: {
		name: 'hyena',
		description: 'Attacks for 2 damage. Can move twice.',
		ai: { abilities: [], canDoubleMove: true },
		attack: { damage: 2 },
		glyph: { char: 'H', class: 'font-creature text-orange-200 z-50' },
		hp: { current: 1, max: 1 },
		statuses: {},
		team: 'enemy',
		threat: 1,
	},
	hydra: {
		name: 'hydra',
		description: 'Attacks for 3 damage. Rapidly heals.',
		ai: { abilities: [] },
		attack: { damage: 3 },
		glyph: { char: 'H', class: 'font-creature text-fuchsia-400 z-50' },
		hp: { current: 12, max: 12 },
		statuses: { 'regen+': true },
		team: 'enemy',
		threat: 10,
	},
	siren: {
		name: 'siren',
		description: "Attacks for 1 damage. Occasionally charms creatures to it's side.",
		ai: {
			abilities: [{ ability: 'sirenCharm', countsAsTurn: true, cooldown: 10, currentCooldown: 10 }],
		},
		attack: { damage: 1 },
		glyph: { char: 'S', class: 'font-creature text-pink-500 z-50' },
		hp: { current: 3, max: 3 },
		statuses: {},
		team: 'enemy',
		threat: 3,
	},
	slime: {
		name: 'slime',
		description: 'Attacks for 1 damage. Slowly heals and splits.',
		ai: {
			abilities: [
				{
					ability: 'slimeSplit',
					cooldown: 0,
					currentCooldown: 0,
					countsAsTurn: false,
				},
			],
		},
		attack: { damage: 1 },
		glyph: { char: 'S', class: 'font-creature text-lime-400 z-50' },
		hp: { current: 2, max: 2 },
		statuses: { regen: true },
		team: 'enemy',
		threat: 3,
	},
	snake: {
		name: 'snake',
		synonyms: ['adder', 'cobra', 'viper'],
		description: 'Attacks for 1 damage and 3 poison',
		ai: { abilities: [] },
		attack: { damage: 1, inflicts: { poisoned: 3 } },
		glyph: { char: 'S', class: 'font-creature text-emerald-500 z-50' },
		hp: { current: 1, max: 1 },
		statuses: {},
		team: 'enemy',
		threat: 1,
	},
	tiger: {
		name: 'tiger',
		description: 'Attacks for 1 damage and 3 turns of bleeding. Can move and attack.',
		ai: { abilities: [], canMoveAndAttack: true },
		attack: { damage: 1, inflicts: { bleeding: 3 } },
		glyph: { char: 'T', class: 'font-creature text-orange-400 z-50' },
		hp: { current: 4, max: 4 },
		statuses: {},
		team: 'enemy',
		threat: 4,
	},
	troll: {
		name: 'troll',
		description: 'Attacks for 2 damage. Steadily heals.',
		ai: { abilities: [] },
		attack: { damage: 2 },
		glyph: { char: 'T', class: 'font-creature text-teal-500 z-50' },
		hp: { current: 10, max: 10 },
		statuses: { regen: true },
		team: 'enemy',
		threat: 5,
	},
} satisfies Record<string, Template>;
